export enum POSITION_ENUM {
  TOP,
  RIGHT,
  BOTTOM,
  LEFT,
  CENTER,
}

export const INIT_POSITION_MAP = {
  [POSITION_ENUM.TOP]: 0,
  [POSITION_ENUM.RIGHT]: 1,
  [POSITION_ENUM.BOTTOM]: 1,
  [POSITION_ENUM.LEFT]: 0,
  [POSITION_ENUM.CENTER]: 0.5,
} as const;
